tiktokadmin/urls.py
from django.conf.urls import patterns, url

from tiktokadmin import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^create/$', views.create, name='create'),
                       url(r'^create/add/$', views.create_post, name='create_post'),
                       url(r'^queue/$', views.queue, name='queue'),
                       url(r'^queue/add/$', views.queue_created, name='queue_created'),
                       url(r'^queue/edit/$', views.queue_edit, name='queue_edit'),
                       url(r'^tweet/edit/$', views.tweet_edit, name='tweet_edit'),
                       url(r'^tweet/final/$', views.tweet_final, name='tweet_final'),
                       url(r'^tweet/delete/$', views.tweet_delete, name='tweet_delete'),
                       url(r'^queue/delete/$', views.queue_delete, name='queue_delete'),
                       url(r'^schedule/$', views.schedule_tweet, name='schedule_tweet'),
                       url(r'^schedule/queue$', views.add_queue, name='add_queue'),
                       url(r'^schedule/queue_done$', views.add_queue_done, name='add_queue_done'),
                       url(r'^responses/$', views.responses, name='responses'),
                       url(r'^responses/manage/$', views.responses_manage, name='responses_manage'),


                       )

tiktoktweet/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from tiktoktweet.settings import STATIC_ROOT

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'tiktoktweet.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^tiktokadmin/', include('tiktokadmin.urls', namespace="tiktokadmin")),
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('',
                        url(r'^static/(.*)$', 'django.views.static.serve', {'document_root': STATIC_ROOT, 'show_indexes' : True}),
                        )

tiktokadmin/models.py
from django.db import models

from cqlengine import columns
from cqlengine.models import Model

# Create your models here.

class Tweets(Model):
    id = columns.UUID(primary_key=True)
    tweet = columns.Text()
    description = columns.Text()
    created = columns.DateTime()
    modified = columns.DateTime()

class Queue(Model):
    id = columns.UUID(primary_key=True)
    name = columns.Text()
    created = columns.DateTime()
    modified = columns.DateTime()

class Tweets_queue(Model):
    queue_id = columns.UUID(primary_key=True)
    time_to_send = columns.DateTime(primary_key=True, clustering_order="DESC")
    tweet_id = columns.UUID(primary_key=True, clustering_order="ASC")


class Queue_tweet_responses(Model):
    queue_id = columns.UUID(primary_key=True)
    time_received = columns.DateTime(primary_key=True, clustering_order="DESC")
    user = columns.Text(primary_key=True)
    tweet_id = columns.UUID()
    response = columns.Text()


class Tweets_sent(Model):
    queue_id = columns.UUID(primary_key=True)
    time_sent = columns.DateTime(primary_key=True, clustering_order="DESC")
    tweet_id = columns.UUID()

class Tweets_sent_by_twitter_id(Model):
    twitter_id = columns.BigInt(primary_key=True)
    queue_id = columns.UUID()
    tweet_id = columns.UUID()

tiktokadmin/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import RequestContext, loader
from tiktokadmin.models import Tweets, Queue, Tweets_queue, Queue_tweet_responses
from tiktokadmin.classes import TweetMetaData
import uuid
from datetime import datetime

# Create your views here.
# Views handle HTTP requests from the user and respond with and appropriate HTTP response

def index(request):
    # view for index main page
    template = loader.get_template('tiktokadmin/index.html')
    context = RequestContext(request)
    return HttpResponse(template.render(context))

def create(request):
    # view for creating a tweet
    template = loader.get_template('tiktokadmin/create.html')
    queue_list = Queue.objects.all()
    context = RequestContext(request, {'queue_list': queue_list})
    return HttpResponse(template.render(context))

def create_post(request):
    # This is a view for sending created tweet to database
    template = loader.get_template('tiktokadmin/create_post.html')
    text = request.POST['tweettext']
    queueid = request.POST['queue_id']
    tweetid = uuid.uuid4()
    if queueid != '0':
        tweet_time = request.POST['when_to_tweet']
        if tweet_time == '':
            template = loader.get_template('tiktokadmin/create_post_no_time.html')
            context = RequestContext(request)
            return HttpResponse(template.render(context))
        tweet_time = datetime.strptime(tweet_time, '%m/%d/%Y %I:%M %p')
        Tweets_queue.create(queue_id = queueid, time_to_send = tweet_time, tweet_id = tweetid)
    Tweets.create(id = tweetid, created = datetime.utcnow(), modified = datetime.utcnow(),  tweet = text)
    context = RequestContext(request, {'text': text})
    return HttpResponse(template.render(context))


def queue(request):
    # This is a view for creating a queue
    template = loader.get_template('tiktokadmin/queue.html')
    queue_list = Queue.objects.all()
    context = RequestContext(request, {'queue_list': queue_list})
    return HttpResponse(template.render(context))

def queue_created(request):
    # view for creating a queue
    template = loader.get_template('tiktokadmin/queue_created.html')
    text = request.POST['queuename']
    if not text:
        return HttpResponse("No queue name was entered")
    Queue.create(id = uuid.uuid4(), created = datetime.utcnow(), modified = datetime.utcnow(),  name = text)
    context = RequestContext(request, {'text': text} )
    return HttpResponse(template.render(context))

def queue_edit(request):
    # This is a view for editing a queue
    template = loader.get_template('tiktokadmin/queue_edit.html')
    queue_id = request.POST['queue_id']
    tweetqueue_list = Tweets_queue.objects.filter(queue_id = queue_id)
    queuelist = Queue.get(id = queue_id)
    # do a foreach loop on tweetqueue_list to get all tweet_ids for retrieving tweets from Tweets table.
    tweet_list = []
    for entry in tweetqueue_list:
        tweet = Tweets.get(id = entry.tweet_id)
        tweet_list.append(TweetMetaData(tweet.id, tweet.tweet, entry.queue_id, entry.time_to_send.strftime("%Y-%m-%d %H:%M:%S")))
    context = RequestContext(request, {'tweet_list': tweet_list,'queue_id': queue_id, 'queuelist': queuelist} )
    return HttpResponse(template.render(context))


def queue_delete(request):
    # view for deleting a queue
    template = loader.get_template('tiktokadmin/queue_deleted.html')
    if 'queue_id' in request.POST:
        queue_id = request.POST['queue_id']
        Tweets_queue.objects(queue_id= queue_id).delete()
        Queue.objects(id= queue_id).delete()
        context = RequestContext(request)
        return HttpResponse(template.render(context))
    else:
        pass


def tweet_edit(request):
    # view for editing a tweet
    if 'queue_id' in request.POST:
        template = loader.get_template('tiktokadmin/tweet_edit.html')
        time_to_send = request.POST['time_to_send']
        tweet_id = request.POST['tweet_id']
        queue_id = request.POST['queue_id']
        tweet_data = Tweets.get(id = tweet_id)
        context = RequestContext(request, {'tweet_data':tweet_data,'queue_id': queue_id, 'time_to_send': time_to_send})
        return HttpResponse(template.render(context))
    else:
        template = loader.get_template('tiktokadmin/tweet_edit.html')
        tweet_id = request.POST['tweet_id']
        tweet_data = Tweets.get(id = tweet_id)
        context = RequestContext(request, {'tweet_data':tweet_data})
        return HttpResponse(template.render(context))

def tweet_final(request):
    template = loader.get_template('tiktokadmin/tweet_final.html')
    if 'queue_id' in request.POST:
        text = request.POST['tweettext']
        old_tweet_time = request.POST['old_tweet_time']
        old_tweet_time = datetime.strptime(old_tweet_time, '%Y-%m-%d %H:%M:%S')
        tweet_time = request.POST['new_time']
        tweet_id = request.POST['tweet_id']
        tweet_time = datetime.strptime(tweet_time, '%m/%d/%Y %I:%M %p')
        queue_id = request.POST['queue_id']
        Tweets.objects(id=tweet_id).update(tweet= text, modified = datetime.utcnow())
        Tweets_queue.objects(queue_id = queue_id, time_to_send = old_tweet_time).delete()
        Tweets_queue.create(queue_id = queue_id, time_to_send = tweet_time, tweet_id = tweet_id)

    else:
        text = request.POST['tweettext']
        tweet_time = request.POST['new_time']
        tweet_id = request.POST['tweet_id']
        Tweets.objects(id=tweet_id).update(tweet= text, modified = datetime.utcnow())
    context = RequestContext(request, {'text':text})
    return HttpResponse(template.render(context))


def schedule_tweet(request):
    template = loader.get_template('tiktokadmin/schedule_tweet.html')
    tweet_list = Tweets.objects.all()
    context = RequestContext(request, {'tweet_list': tweet_list})
    return HttpResponse(template.render(context))


def responses(request):
    template = loader.get_template('tiktokadmin/responses.html')
    queue_list = Queue.objects.all()
    context = RequestContext(request, {'queue_list': queue_list})
    return HttpResponse(template.render(context))

def responses_manage(request):
    template = loader.get_template('tiktokadmin/responses_manage.html')
    queue_id = request.POST['queue_id']
    responsequeue_list = Queue_tweet_responses.filter(queue_id = queue_id)
    queuelist = Queue.get(id = queue_id)
    context = RequestContext(request, {'responsequeue_list': responsequeue_list, 'queuelist': queuelist})
    return HttpResponse(template.render(context))

def tweet_delete(request):
    # To come
    return HttpResponse("hi")

def add_queue(request):
    template = loader.get_template('tiktokadmin/add_queue.html')
    tweet_id = request.POST['tweet_id']
    queue_list = Queue.objects.all()
    context = RequestContext(request, {'queue_list': queue_list, 'tweet_id': tweet_id})
    return HttpResponse(template.render(context))

def add_queue_done(request):
    template = loader.get_template('tiktokadmin/queue_done.html')
    tweet_id = request.POST['tweet_id']
    when_to_tweet = request.POST['when_to_tweet']
    tweet_time = datetime.strptime(when_to_tweet, '%m/%d/%Y %I:%M %p')
    queue_id = request.POST['queue_id']
    Tweets_queue.create(queue_id = queue_id, time_to_send = tweet_time, tweet_id = tweet_id)
    context = RequestContext(request, {'queue_id': queue_id, 'when_to_tweet': when_to_tweet})
    return HttpResponse(template.render(context))

tiktokadmin/templates/tiktokadmin/add_queue.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <!-- ... -->
    <script type="text/javascript" src="/static/bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/jquery-validation/dist/jquery.validate.js"></script>
    <script type="text/javascript" src="/static/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">


    <!-- Bootstrap Core CSS -->
    <link href="/static/bower_components/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/static/bower_components/startbootstrap-sb-admin-2/dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/bower_components/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/static/bower_components/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">



</head>

<div style="background:#eef3ff !important" class="jumbotron">

    <div class="row">

        <div class="col-lg-8 col-md-offset-2"><h1 class="text-left text-primary" style="@font-family-monospace:Consolas" >TikTok Tweet</h1>
            <p> A tweet scheduler, written in Python and backed by the power of Cassandra</p>
            <form action="https://github.com/beccam/tiktoktweet">
                <input class="btn btn-primary" type="submit" value="View on Github" id="jsSubmit1" >
            </form></div>


        <div><img src="http://www.webwizardofoz.com/images/Tiktok.png" class="img-circle"></div>

    </div>

</div>


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="http://127.0.0.1:8000/tiktokadmin/create/">Create new Tweet<span class="sr-only">(current)</span></a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/schedule/">Schedule a Tweet </a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/queue/">Manage Queues</a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/responses/">Manage Responses</a></li>

            </ul>

        </div>



        <div class="row">
            <div class="col-md-6 col-md-offset-3">
<body>

<form action="{% url 'tiktokadmin:add_queue_done'  %}" method="post">
    {% csrf_token %}
    <input type="hidden" name = 'tweet_id' value='{{tweet_id}}' >
    <label>Add to queue:</label>
    <select class="form-control" name = "queue_id">
        {% for queue in queue_list %}
        <option value = "{{queue.id}}">{{queue.name}}</option>
        {% endfor %}
    </select>
    <br><br>
    <label>Time to tweet</label>

    <div class="container">
        <div class="row">
            <div class='col-sm-6'>
                <div class="form-group">
                    <div class='input-group date' id='datetimepicker1'>
                        <input type='text' class="form-control" name="when_to_tweet" required>
                    <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
                    </span>
                    </div>
                </div>
            </div>
            <script type="text/javascript">
                $(function () {
                    $('#datetimepicker1').datetimepicker();
                });
            </script>
        </div>
    </div>
    <br>

    <br>

    <input type="submit" value="Submit"/>

</form>
<br>
<form action="/tiktokadmin/">
    <input type="submit" value="Home" id="jsSubmit1" >
</form>

</body>
</html>

tiktokadmin/templates/tiktokadmin/create_post.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <!-- ... -->
    <script type="text/javascript" src="/static/bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/jquery-validation/dist/jquery.validate.js"></script>
    <script type="text/javascript" src="/static/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">


    <!-- Bootstrap Core CSS -->
    <link href="/static/bower_components/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/static/bower_components/startbootstrap-sb-admin-2/dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/bower_components/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/static/bower_components/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">



</head>

<div style="background:#eef3ff !important" class="jumbotron">

    <div class="row">

        <div class="col-lg-8 col-md-offset-2"><h1 class="text-left text-primary" style="@font-family-monospace:Consolas" >TikTok Tweet</h1>
            <p> A tweet scheduler, written in Python and backed by the power of Cassandra</p>
            <form action="https://github.com/beccam/tiktoktweet">
                <input class="btn btn-primary" type="submit" value="View on Github" id="jsSubmit1" >
            </form></div>


        <div><img src="http://www.webwizardofoz.com/images/Tiktok.png" class="img-circle"></div>

    </div>

</div>


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="http://127.0.0.1:8000/tiktokadmin/create/">Create new Tweet<span class="sr-only">(current)</span></a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/schedule/">Schedule a Tweet </a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/queue/">Manage Queues</a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/responses/">Manage Responses</a></li>

            </ul>

        </div>



        <div class="row">
            <div class="col-md-6 col-md-offset-3">

<p>Here is your new tweet:</p>
<p >{{ text }}</p>

<form action="/tiktokadmin/">
    <input type="submit" value="Home" id="jsSubmit1" >
</form>

tiktokadmin/templates/tiktokadmin/queue.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <!-- ... -->
    <script type="text/javascript" src="/static/bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/jquery-validation/dist/jquery.validate.js"></script>
    <script type="text/javascript" src="/static/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">


    <!-- Bootstrap Core CSS -->
    <link href="/static/bower_components/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/static/bower_components/startbootstrap-sb-admin-2/dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/bower_components/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/static/bower_components/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">



</head>

<div style="background:#eef3ff !important" class="jumbotron">

    <div class="row">

        <div class="col-lg-8 col-md-offset-2"><h1 class="text-left text-primary" style="@font-family-monospace:Consolas" >TikTok Tweet</h1>
            <p> A tweet scheduler, written in Python and backed by the power of Cassandra</p>
            <form action="https://github.com/beccam/tiktoktweet">
                <input class="btn btn-primary" type="submit" value="View on Github" id="jsSubmit1" >
            </form></div>


        <div><img src="http://www.webwizardofoz.com/images/Tiktok.png" class="img-circle"></div>

    </div>

</div>


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="http://127.0.0.1:8000/tiktokadmin/create/">Create new Tweet<span class="sr-only">(current)</span></a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/schedule/">Schedule a Tweet </a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/queue/">Manage Queues</a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/responses/">Manage Responses</a></li>

            </ul>

        </div>



        <div class="row">
            <div class="col-md-6 col-md-offset-3">
<body>
<h2>Manage a queue</h2>

<form action="{% url 'tiktokadmin:queue_edit'  %}" method="post">
    {% csrf_token %}


    <label>Select a queue to edit:</label>
    <select class="form-control" name = "queue_id">
        {% for queue in queue_list %}
        <option value = "{{queue.id}}">{{queue.name}}</option>
        {% endfor %}
    </select>
    <input class="btn btn-info btn-xs" type="submit" value="Submit"/>

</form>

<form action="{% url 'tiktokadmin:queue_created'  %}" method="post">
    {% csrf_token %}

    Create a new queue:<input class="medium form-control" type="text" name="queuename" required="">
    <input class="btn btn-info btn-xs" type="submit" value="Submit"/>
</form>
<br>
<form action="/tiktokadmin/">
    <input class="btn btn-primary" type="submit" value="Home" id="jsSubmit1" >
</form>

</body>
</html>

tiktokadmin/templates/tiktokadmin/queue_edit.html
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8">

    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <!-- ... -->
    <script type="text/javascript" src="/static/bower_components/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/static/bower_components/jquery-validation/dist/jquery.validate.js"></script>
    <script type="text/javascript" src="/static/bower_components/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <link rel="stylesheet" href="/static/bower_components/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/static/bower_components/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">


    <!-- Bootstrap Core CSS -->
    <link href="/static/bower_components/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/bower_components/metisMenu/dist/metisMenu.min.css" rel="stylesheet">

    <!-- Timeline CSS -->
    <link href="/static/bower_components/startbootstrap-sb-admin-2/dist/css/timeline.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/bower_components/startbootstrap-sb-admin-2/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="/static/bower_components/morrisjs/morris.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">



</head>

<div style="background:#eef3ff !important" class="jumbotron">

    <div class="row">

        <div class="col-lg-8 col-md-offset-2"><h1 class="text-left text-primary" style="@font-family-monospace:Consolas" >TikTok Tweet</h1>
            <p> A tweet scheduler, written in Python and backed by the power of Cassandra</p>
            <form action="https://github.com/beccam/tiktoktweet">
                <input class="btn btn-primary" type="submit" value="View on Github" id="jsSubmit1" >
            </form></div>


        <div><img src="http://www.webwizardofoz.com/images/Tiktok.png" class="img-circle"></div>

    </div>

</div>


<div class="container-fluid">
    <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
            <ul class="nav nav-sidebar">
                <li class="active"><a href="http://127.0.0.1:8000/tiktokadmin/create/">Create new Tweet<span class="sr-only">(current)</span></a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/schedule/">Schedule a Tweet </a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/queue/">Manage Queues</a></li>
                <li><a href="http://127.0.0.1:8000/tiktokadmin/responses/">Manage Responses</a></li>

            </ul>

        </div>



        <div class="row">
            <div class="col-md-6 col-md-offset-3">
<body>

    <h2>Manage a queue</h2>
    <h3>{{ queuelist.name }}</h3>
    <table class="table table-hover">
        {% for tweets in tweet_list %}
        <tr>
            <td>
                <form action="{% url 'tiktokadmin:tweet_edit'  %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name = tweet_id ><input type="hidden" name = 'tweet_id' value='{{tweets.tweet_id}}' >{{tweets.tweet}}
                    <input type="hidden" name = 'queue_id' value='{{queue_id}}' > <input type="hidden" name = 'time_to_send' value='{{tweets.time_to_send}}' >
                <td>  <input type="submit" value="Edit" > </td>
                </form>
            </td>
        </tr>
        {% endfor %}
    </table>


    <br>
    <form action="{% url 'tiktokadmin:queue_delete'  %}" method="post">
        {% csrf_token %}
    <input type="checkbox" name="queue_id" value='{{queue_id}}'>Delete queue
    <br>
    <input class="btn btn-info btn-xs" type="submit" value="Submit"/></form>

    <form action="/tiktokadmin/">
        <input class="btn btn-primary" type="submit" value="Home" id="jsSubmit1" >
    </form>

</body>
</html>